# -*- coding: utf-8 -*-
"""Despliegue_stroke.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1S3T8Lpd7L0nvgYjevbxfNHLWoUZ3-ZGh

# Despliegue

- Cargamos el modelo
- Cargamos los datos futuros (interfaz gráfica)
- Preparar los datos futuros
- Aplicamos el modelo para la predicción
"""

#Cargamos librerías principales

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

import pickle

filename = 'modelo-class.pkl'
modelo, label_encoder, variables, min_max_scaler = pickle.load(open(filename, 'rb'))

#Interfaz gráfica
#Se crea interfaz gráfica con streamlit para captura de los datos

import streamlit as st

st.title('Predicción de riesgo de ACV (Stroke)')

age = st.slider('Edad', min_value=1, max_value=100, value=45, step=1)

avg_glucose_level = st.number_input('Nivel promedio de glucosa (mg/dL)', min_value=50.0, max_value=300.0, value=100.0, step=0.1)

smoking_status = st.selectbox('Estado de fumador', [
    'never smoked',
    'formerly smoked',
    'smokes',
    'Unknown'
])

hypertension = st.selectbox('¿Tiene hipertensión?', ['No', 'Sí'])

heart_disease = st.selectbox('¿Tiene enfermedad cardíaca?', ['No', 'Sí'])

ever_married = st.selectbox('¿Ha estado casado/a?', ['No', 'Sí'])

# Dataframe
# Se convierten las variables categóricas a dummies manualmente

smoking_formerly  = 1 if smoking_status == 'formerly smoked' else 0
smoking_never     = 1 if smoking_status == 'never smoked'    else 0
smoking_unknown   = 1 if smoking_status == 'Unknown'         else 0
smoking_smokes    = 1 if smoking_status == 'smokes'          else 0

hypertension_val  = 1 if hypertension  == 'Sí' else 0
heart_disease_val = 1 if heart_disease == 'Sí' else 0
ever_married_val  = 1 if ever_married  == 'Sí' else 0

datos = [[age, avg_glucose_level,
          smoking_formerly, smoking_never, smoking_unknown, smoking_smokes,
          hypertension_val, heart_disease_val, ever_married_val]]

data = pd.DataFrame(datos, columns=[
    'age',
    'avg_glucose_level',
    "smoking_status_'formerly smoked'",
    "smoking_status_'never smoked'",
    'smoking_status_Unknown',
    'smoking_status_smokes',
    'hypertension_Yes',
    'heart_disease_Yes',
    'ever_married_Yes'
])

data.head()

#Se realiza la preparación
data_preparada = data.copy()

#Se adicionan las columnas faltantes y se reordena igual que en el entrenamiento
data_preparada = data_preparada.reindex(columns=variables, fill_value=0)
data_preparada.head()

#Se normalizan age y avg_glucose_level con el scaler guardado
#En despliegue no se llama fit, solo transform
data_preparada[['age', 'avg_glucose_level']] = min_max_scaler.transform(data_preparada[['age', 'avg_glucose_level']])
data_preparada.head()

"""# Predicciones"""

#Hacemos la predicción con el modelo KNN
Y_pred = modelo.predict(data_preparada)

#Decodificamos la predicción con el label encoder
Y_pred_label = label_encoder.inverse_transform(Y_pred)
print(Y_pred_label)

data['Prediccion'] = Y_pred_label
data.head()

#Mostramos el resultado en la interfaz
resultado = Y_pred_label[0]

if resultado == 'Yes':
    st.error(f'⚠️ Resultado: RIESGO DE ACV detectado')
else:
    st.success(f'✅ Resultado: Sin riesgo de ACV')

st.warning('El modelo tiene un error del 8%')